{
 "title": "vLLM",
 "description": "Monitoring vLLM Inference Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "model_name", "label": "model_name", "query": { "query": "label_values(model_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Iteration Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Per Output Token Latency",
     "type": "timeseries",
     "description": "Inter token latency in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "rate(vllm:time_per_output_token_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_per_output_token_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
       "legendFormat": "Mean"
      }
     ]
    },
    {
     "title": "Time To First Token Latency",
     "type": "timeseries",
     "description": "P50, P90, P95, and P99 TTFT latency in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "rate(vllm:time_to_first_token_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "E2E Request Latency",
     "type": "timeseries",
     "description": "End to end request latency measured in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Finish Reason",
     "type": "timeseries",
     "description": "Number of finished requests by their finish reason: either an EOS token was generated or the max sequence length was reached.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=\"$model_name\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Inference Time",
     "type": "timeseries",
     "description": "E2E Latency = Inference Time + Queue Time\nInference Time = Prefill Time + Decode Time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:request_inference_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:request_inference_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_inference_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_inference_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "rate(vllm:request_inference_time_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:request_inference_time_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Request Queue Time",
     "type": "timeseries",
     "description": "E2E Latency = Inference Time + Queue Time\nInference Time = Prefill Time + Decode Time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "rate(vllm:request_queue_time_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:request_queue_time_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
       "legendFormat": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "System State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler State",
     "type": "timeseries",
     "description": "Number of requests in RUNNING, WAITING, and SWAPPED state",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vllm:num_requests_running{model_name=\"$model_name\"}",
       "legendFormat": "Num Running"
      },
      {
       "expr": "vllm:num_requests_swapped{model_name=\"$model_name\"}",
       "legendFormat": "Num Swapped"
      },
      {
       "expr": "vllm:num_requests_waiting{model_name=\"$model_name\"}",
       "legendFormat": "Num Waiting"
      }
     ]
    },
    {
     "title": "Cache Utilization",
     "type": "timeseries",
     "description": "Percentage of used cache blocks by vLLM.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "vllm:gpu_cache_usage_perc{model_name=\"$model_name\"}",
       "legendFormat": "GPU Cache Usage"
      },
      {
       "expr": "vllm:cpu_cache_usage_perc{model_name=\"$model_name\"}",
       "legendFormat": "CPU Cache Usage"
      }
     ]
    },
    {
     "title": "Token Throughput",
     "type": "timeseries",
     "description": "Number of tokens processed per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(vllm:prompt_tokens_total{model_name=\"$model_name\"}[$__rate_interval])",
       "legendFormat": "Prompt Tokens/Sec"
      },
      {
       "expr": "rate(vllm:generation_tokens_total{model_name=\"$model_name\"}[$__rate_interval])",
       "legendFormat": "Generation Tokens/Sec"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Shape",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Prompt Length",
     "type": "heatmap",
     "description": "Heatmap of request prompt length",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Request Generation Length",
     "type": "heatmap",
     "description": "Heatmap of request generation length",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=\"$model_name\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}